import { Category } from "../types/Category";

export const navs: Category[] = [
  {
    id: 31,
    parent_id: null,
    lft: 51,
    rght: 54,
    level: 0,
    title: "Bakery",
    slug: "bakery-2",
    description: "",
    has_landing_page: false,
    sort: null,
    show_on_menu: true,
    created: "2024-08-19T11:40:48+02:00",
    modified: "2024-08-19T11:51:12+02:00",
    deleted: null,
    children: [
      {
        id: 32,
        parent_id: 31,
        lft: 52,
        rght: 53,
        level: 1,
        title: "Fresh Rolls",
        slug: "fresh-rolls",
        description: "",
        has_landing_page: false,
        sort: null,
        show_on_menu: true,
        created: "2024-08-19T11:41:19+02:00",
        modified: "2024-08-19T11:51:50+02:00",
        deleted: null,
        children: [],
        display_title: "Fresh Rolls",
        path: "fresh-rolls",
      },
    ],
    display_title: "Bakery",
    path: "bakery-2",
  },
  {
    id: 43,
    parent_id: null,
    lft: 61,
    rght: 62,
    level: 0,
    title: "Braai",
    slug: "braai",
    description: "<p>Outdoor</p>",
    has_landing_page: false,
    sort: null,
    show_on_menu: true,
    created: "2024-08-27T16:39:55+02:00",
    modified: "2024-08-27T16:39:55+02:00",
    deleted: null,
    children: [],
    display_title: "Braai",
    path: "braai",
  },
  {
    id: 2,
    parent_id: null,
    lft: 1,
    rght: 8,
    level: 0,
    title: "FOOD",
    slug: "food",
    description: "",
    has_landing_page: false,
    sort: 0,
    show_on_menu: true,
    created: "2024-08-19T08:16:11+02:00",
    modified: "2024-08-29T09:10:39+02:00",
    deleted: null,
    children: [
      {
        id: 26,
        parent_id: 2,
        lft: 2,
        rght: 3,
        level: 1,
        title: "Fruit & Vegetables",
        slug: "fruit-vegetables",
        description: "",
        has_landing_page: false,
        sort: 0,
        show_on_menu: true,
        created: "2024-08-19T08:54:26+02:00",
        modified: "2024-08-19T08:54:26+02:00",
        deleted: null,
        children: [],
        display_title: "Fruit & Vegetables",
        path: "fruit-vegetables",
      },
      {
        id: 27,
        parent_id: 2,
        lft: 4,
        rght: 5,
        level: 1,
        title: "Meat, Poultry & Fish",
        slug: "meat-poultry-fish",
        description: "",
        has_landing_page: false,
        sort: 1,
        show_on_menu: true,
        created: "2024-08-19T08:54:53+02:00",
        modified: "2024-08-19T08:54:53+02:00",
        deleted: null,
        children: [],
        display_title: "Meat, Poultry & Fish",
        path: "meat-poultry-fish",
      },
      {
        id: 28,
        parent_id: 2,
        lft: 6,
        rght: 7,
        level: 1,
        title: "Meat, Dairy & Eggs",
        slug: "meat-dairy-eggs",
        description: "",
        has_landing_page: false,
        sort: 2,
        show_on_menu: true,
        created: "2024-08-19T08:55:18+02:00",
        modified: "2024-08-19T08:55:18+02:00",
        deleted: null,
        children: [],
        display_title: "Meat, Dairy & Eggs",
        path: "meat-dairy-eggs",
      },
    ],
    display_title: "Food",
    path: "food",
  },
  {
    id: 5,
    parent_id: null,
    lft: 9,
    rght: 46,
    level: 0,
    title: "Drinks",
    slug: "drinks",
    description: "",
    has_landing_page: false,
    sort: 1,
    show_on_menu: true,
    created: "2024-08-19T08:18:27+02:00",
    modified: "2024-09-09T12:23:41+02:00",
    deleted: null,
    children: [
      {
        id: 11,
        parent_id: 5,
        lft: 10,
        rght: 11,
        level: 1,
        title: "Soft Drinks",
        slug: "soft-drinks",
        description: "<p>Soft Drinks</p>",
        has_landing_page: false,
        sort: 0,
        show_on_menu: true,
        created: "2024-08-19T08:26:01+02:00",
        modified: "2024-08-19T08:26:01+02:00",
        deleted: null,
        children: [],
        display_title: "Soft Drinks",
        path: "soft-drinks",
      },
      {
        id: 15,
        parent_id: 5,
        lft: 14,
        rght: 15,
        level: 1,
        title: "Juices & Smoothies",
        slug: "juices-smoothies",
        description: "<p>Juices & Smoothies</p>",
        has_landing_page: false,
        sort: 1,
        show_on_menu: true,
        created: "2024-08-19T08:39:47+02:00",
        modified: "2024-08-19T08:39:47+02:00",
        deleted: null,
        children: [],
        display_title: "Juices & Smoothies",
        path: "juices-smoothies",
      },
      {
        id: 14,
        parent_id: 5,
        lft: 12,
        rght: 13,
        level: 1,
        title: "Bottled Water",
        slug: "bottled-water",
        description: "<p>Bottled Water</p>",
        has_landing_page: false,
        sort: 3,
        show_on_menu: true,
        created: "2024-08-19T08:38:31+02:00",
        modified: "2024-08-19T08:38:40+02:00",
        deleted: null,
        children: [],
        display_title: "Bottled Water",
        path: "bottled-water",
      },
      {
        id: 16,
        parent_id: 5,
        lft: 16,
        rght: 17,
        level: 1,
        title: "Concentrates",
        slug: "concentrates",
        description: "<p>Concentrates</p>",
        has_landing_page: false,
        sort: 4,
        show_on_menu: true,
        created: "2024-08-19T08:40:06+02:00",
        modified: "2024-08-19T08:40:06+02:00",
        deleted: null,
        children: [],
        display_title: "Concentrates",
        path: "concentrates",
      },
      {
        id: 17,
        parent_id: 5,
        lft: 18,
        rght: 45,
        level: 1,
        title: "Alcohol",
        slug: "alcohol",
        description: "",
        has_landing_page: false,
        sort: 8,
        show_on_menu: true,
        created: "2024-08-19T08:40:27+02:00",
        modified: "2024-08-28T16:52:19+02:00",
        deleted: null,
        children: [
          {
            id: 44,
            parent_id: 17,
            lft: 41,
            rght: 42,
            level: 2,
            title: "Beer",
            slug: "beer",
            description: "<p>Canned Beer</p>",
            has_landing_page: false,
            sort: null,
            show_on_menu: true,
            created: "2024-08-27T16:41:06+02:00",
            modified: "2024-08-27T16:41:06+02:00",
            deleted: null,
            children: [],
            display_title: "Beer",
            path: "beer",
          },
          {
            id: 45,
            parent_id: 17,
            lft: 43,
            rght: 44,
            level: 2,
            title: "Wine Two",
            slug: "wine-two",
            description: "",
            has_landing_page: false,
            sort: null,
            show_on_menu: true,
            created: "2024-09-11T15:54:32+02:00",
            modified: "2024-09-11T15:55:50+02:00",
            deleted: null,
            children: [],
            display_title: "Wine Two",
            path: "wine-two",
          },
          {
            id: 19,
            parent_id: 17,
            lft: 21,
            rght: 22,
            level: 2,
            title: "Spirits",
            slug: "spirits",
            description: "",
            has_landing_page: false,
            sort: 1,
            show_on_menu: true,
            created: "2024-08-19T08:41:03+02:00",
            modified: "2024-08-27T16:36:27+02:00",
            deleted: null,
            children: [],
            display_title: "Spirits",
            path: "spirits",
          },
          {
            id: 18,
            parent_id: 17,
            lft: 19,
            rght: 20,
            level: 2,
            title: "Beer And Cider",
            slug: "beer-and-cider",
            description: "",
            has_landing_page: false,
            sort: 3,
            show_on_menu: true,
            created: "2024-08-19T08:40:47+02:00",
            modified: "2024-08-27T16:45:00+02:00",
            deleted: null,
            children: [],
            display_title: "Beer And Cider",
            path: "beer-and-cider",
          },
          {
            id: 20,
            parent_id: 17,
            lft: 23,
            rght: 40,
            level: 2,
            title: "Wine",
            slug: "wine",
            description: "",
            has_landing_page: true,
            sort: 3,
            show_on_menu: true,
            created: "2024-08-19T08:41:20+02:00",
            modified: "2024-09-11T15:53:42+02:00",
            deleted: null,
            children: [
              {
                id: 46,
                parent_id: 20,
                lft: 30,
                rght: 31,
                level: 3,
                title: "Sparkling Wine",
                slug: "sparkling-wine",
                description: "",
                has_landing_page: false,
                sort: null,
                show_on_menu: true,
                created: "2024-09-12T07:04:52+02:00",
                modified: "2024-09-12T07:04:52+02:00",
                deleted: null,
                children: [],
                display_title: "Sparkling Wine",
                path: "sparkling-wine",
              },
              {
                id: 47,
                parent_id: 20,
                lft: 32,
                rght: 33,
                level: 3,
                title: "Rose",
                slug: "rose",
                description: "",
                has_landing_page: false,
                sort: null,
                show_on_menu: true,
                created: "2024-09-12T07:05:02+02:00",
                modified: "2024-09-12T07:05:02+02:00",
                deleted: null,
                children: [],
                display_title: "Rose",
                path: "rose",
              },
              {
                id: 48,
                parent_id: 20,
                lft: 34,
                rght: 35,
                level: 3,
                title: "Merlot",
                slug: "merlot",
                description: "",
                has_landing_page: false,
                sort: null,
                show_on_menu: true,
                created: "2024-09-12T07:05:13+02:00",
                modified: "2024-09-12T07:05:13+02:00",
                deleted: null,
                children: [],
                display_title: "Merlot",
                path: "merlot",
              },
              {
                id: 49,
                parent_id: 20,
                lft: 36,
                rght: 37,
                level: 3,
                title: "Cabernet Sauvignon",
                slug: "cabernet-sauvignon",
                description: "",
                has_landing_page: false,
                sort: null,
                show_on_menu: true,
                created: "2024-09-12T07:05:26+02:00",
                modified: "2024-09-12T07:05:26+02:00",
                deleted: null,
                children: [],
                display_title: "Cabernet Sauvignon",
                path: "cabernet-sauvignon",
              },
              {
                id: 50,
                parent_id: 20,
                lft: 38,
                rght: 39,
                level: 3,
                title: "Pinotage",
                slug: "pinotage",
                description: "",
                has_landing_page: false,
                sort: null,
                show_on_menu: true,
                created: "2024-09-12T07:05:35+02:00",
                modified: "2024-09-12T07:05:35+02:00",
                deleted: null,
                children: [],
                display_title: "Pinotage",
                path: "pinotage",
              },
              {
                id: 21,
                parent_id: 20,
                lft: 24,
                rght: 25,
                level: 3,
                title: "Red Wine",
                slug: "red-wine",
                description: "",
                has_landing_page: false,
                sort: 0,
                show_on_menu: true,
                created: "2024-08-19T08:41:44+02:00",
                modified: "2024-09-02T11:26:58+02:00",
                deleted: null,
                children: [],
                display_title: "Red Wine",
                path: "red-wine",
              },
              {
                id: 22,
                parent_id: 20,
                lft: 26,
                rght: 27,
                level: 3,
                title: "White Wine",
                slug: "white-wine",
                description: "",
                has_landing_page: false,
                sort: 1,
                show_on_menu: true,
                created: "2024-08-19T08:42:08+02:00",
                modified: "2024-08-19T08:42:22+02:00",
                deleted: null,
                children: [],
                display_title: "White Wine",
                path: "white-wine",
              },
              {
                id: 25,
                parent_id: 20,
                lft: 28,
                rght: 29,
                level: 3,
                title: "Red Blends",
                slug: "red-blends",
                description: "",
                has_landing_page: false,
                sort: 4,
                show_on_menu: true,
                created: "2024-08-19T08:43:12+02:00",
                modified: "2024-08-27T16:42:17+02:00",
                deleted: null,
                children: [],
                display_title: "Red Blends",
                path: "red-blends",
              },
            ],
            display_title: "Wine",
            path: "wine",
          },
        ],
        display_title: "Alcohol",
        path: "alcohol",
      },
    ],
    display_title: "Drinks",
    path: "drinks",
  },
  {
    id: 6,
    parent_id: null,
    lft: 47,
    rght: 48,
    level: 0,
    title: "Home",
    slug: "home",
    description: "",
    has_landing_page: false,
    sort: 2,
    show_on_menu: true,
    created: "2024-08-19T08:21:49+02:00",
    modified: "2024-09-12T09:04:56+02:00",
    deleted: null,
    children: [],
    display_title: "Home",
    path: "home",
  },
  {
    id: 7,
    parent_id: null,
    lft: 47,
    rght: 48,
    level: 0,
    title: "Hygiene",
    slug: "hygiene",
    description: "<p>Hygiene</p>",
    has_landing_page: false,
    sort: 3,
    show_on_menu: true,
    created: "2024-08-19T08:22:08+02:00",
    modified: "2024-08-19T08:22:08+02:00",
    deleted: null,
    children: [],
    display_title: "Hygiene",
    path: "hygiene",
  },
  {
    id: 9,
    parent_id: null,
    lft: 49,
    rght: 50,
    level: 0,
    title: "Baby",
    slug: "baby",
    description: "<p>Baby</p>",
    has_landing_page: false,
    sort: 4,
    show_on_menu: true,
    created: "2024-08-19T08:24:49+02:00",
    modified: "2024-08-19T08:24:49+02:00",
    deleted: null,
    children: [],
    display_title: "Baby",
    path: "baby",
  },
  {
    id: 10,
    parent_id: null,
    lft: 49,
    rght: 50,
    level: 0,
    title: "Pet",
    slug: "pet",
    description: "<p>Pet</p>",
    has_landing_page: false,
    sort: 5,
    show_on_menu: true,
    created: "2024-08-19T08:25:08+02:00",
    modified: "2024-08-19T08:25:08+02:00",
    deleted: null,
    children: [],
    display_title: "Pet",
    path: "pet",
  },
  {
    id: 8,
    parent_id: null,
    lft: 49,
    rght: 50,
    level: 0,
    title: "Health",
    slug: "health",
    description: "<p>Health</p>",
    has_landing_page: false,
    sort: 7,
    show_on_menu: true,
    created: "2024-08-19T08:24:25+02:00",
    modified: "2024-08-19T08:39:19+02:00",
    deleted: null,
    children: [],
    display_title: "Health",
    path: "health",
  },
];
